[package]
name = "adapter"
version = "0.1.0"
edition = "2018"

[[bin]] # Bin to run the HelloWorld gRPC server
name = "helloworld-server"
path = "src/server.rs"

[[bin]] # Bin to run the HelloWorld gRPC client
name = "helloworld-client"
path = "src/client.rs"

[dependencies]
tonic = "0.5"
prost = "0.8"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }

[dev-dependencies]
serde = { version = "*", features = ["derive"] }
serde_with = "*"
serde_yaml = "*"

chrono = { version = "*", features = ["serde"] }
url = { version = "*", features = ["serde"] }
thiserror = "*"  # Structured error derivations

rand = "^0.8"
regex = "*"
libc = "*"

[build-dependencies]
tonic-build = "0.5"
